### ISSUE TITLE
 Upgrade the kernel to version 6.8

### ISSUE THREAD

**Issue by breeze303** [namiltd/openwrt#18]
Hello, I'd like to ask for some advice. I've recently upgraded the kernel to version 6.8, and there are some aspects that I don't quite understand at the moment. I'm curious about how the patches in the target/linux/generic file are updated with kernel.org. Thank you very much for your help. Here is my link: https://github.com/breeze303/x86-6.8

### OpenWrt version

kernel 6.8

### OpenWrt release

kernel 6.8

### OpenWrt target/subtarget

kernel 6.8

### Device

x86-64

**Comment by breeze303** [comment]
![d0d07cb3c85693963ffb795042d82712](https://github.com/namiltd/openwrt/assets/122870904/b541c218-0d8f-4fdd-ac3d-e0f6e26ef731)
Now I am able to boot it up in the virtual machine.

**Comment by namiltd** [comment]
In short:
When changing versions, you need to update patches and config yourself
First via: scripts\kernel_bump.sh
Patches should, of course, be reviewed, removing unnecessary ones or correcting some.
Change KERNEL_PATCHVER to new value and then:
make kernel_oldconfig
make kernel_oldconfig CONFIG_TARGET=subtarget

**Comment by namiltd** [comment]
This is not a bug. Please post your questions at https://forum.openwrt.org/c/devel/8

**Comment by breeze303** [comment]
Okay, thank you.
