### ISSUE TITLE
23.05.4 or 23.05.5? 

### ISSUE THREAD

**Issue by arkuid** [namiltd/openwrt#36]
Hello,  what to choose :openwrt-23.05.4-rtl8367cd or openwrt-23.05.5-rtl8367cd? 
Thanks.

**Comment by namiltd** [comment]
Both work but my tests have shown that the older version (23.05.4) is more stable.

**Comment by arkuid** [comment]
Thanks. Is Offload still not working?

**Comment by namiltd** [comment]
unfortunately yes

**Comment by arkuid** [comment]
Okay. Thank you.
